### ISSUE TITLE
Anchor Server Roadmap

### ISSUE THREAD

**Issue by vitchor** [stellar/stellar-anchor-server#137]
### High priority

- [x] (#141) Define a way to modularize our implementation and the anchors’, so they can easily customize the parts that are needed (without having to fork all the codebase) (Related: #117)
- [x] Add information about the development flow with Docker on the README: document how to point a local `runserver` to point to the containers for Redis, Database, etc.
- [ ] Implement the new designs for the interactive flow
- [ ] Try out PyCharm and see if Intellisense works better. If it does, add that to README as a recommended IDE for better development workflow
- [ ] (#95) Ensure we address all anchor pain points
- [ ] (#134) Implement the new airdrop / deposit scheme 
- [ ] (#121) Use autocomplete on the interactive form contents
- [ ] Figure out the best way to handle error tracking (Sentry or a generic approach?)

### Next
- [ ] (#135) Support different issuers for assets
- [ ] Update codebase to use the V2 of the Stellar Python SDK
- [ ] (#86) Pre-issue assets on testnet
- [ ] (#128) Document how to get working on Ubuntu 18.04
- [ ] (#118) Allow for error webhooks
- [ ] (#124) Update title of interactive flow

**Comment by JakeUrban** [comment]
This roadmap no longer reflects the priorities of the team managing this project. See the issues on django-polaris or the anchor team sprint board: https://github.com/orgs/stellar/projects/14
